#pragma once

#include "responseheader.h"

enum class LoggingRegister : uint8_t {
    ENABLE = 1,
    TRIGGER,
    REMOVE,
    TIME,
    LENGTH,
    READOUT,
    READOUT_NOTIFY,
    READOUT_PROGRESS,
    REMOVE_ENTRIES,
    REMOVE_ALL,
    CIRCULAR_BUFFER,
    READOUT_PAGE_COMPLETED = 0xd,
    READOUT_PAGE_CONFIRM,
};

const ResponseHeader LOGGING_RESPONSE_TRIGGER_HEADER(MBL_MW_MODULE_LOGGING, ORDINAL(LoggingRegister::TRIGGER)),
        LOGGING_RESPONSE_LENGTH_HEADER(MBL_MW_MODULE_LOGGING, READ_REGISTER(ORDINAL(LoggingRegister::LENGTH))),
        LOGGING_RESPONSE_NOTIFY_HEADER(MBL_MW_MODULE_LOGGING, ORDINAL(LoggingRegister::READOUT_NOTIFY)),
        LOGGING_RESPONSE_PROGRESS_HEADER(MBL_MW_MODULE_LOGGING, ORDINAL(LoggingRegister::READOUT_PROGRESS)),
        LOGGING_RESPONSE_PAGE_COMPLETED_HEADER(MBL_MW_MODULE_LOGGING, ORDINAL(LoggingRegister::READOUT_PAGE_COMPLETED));
